---
  name: "Timeago"
  stable: "0.10.0"
  copyright: "Copyright (c) 2008-2011, Ryan McGeary."
  license: "MIT License"
  author: "Ryan McGeary"
  url: "http://timeago.yarp.com/"
  description: "Timeago is a jQuery plugin that makes it easy to support automatically updating fuzzy timestamps (e.g. \"4 minutes ago\" or \"about 1 day ago\")."
  latest: "0.10.0"
  packages:
    0.10.0:
      source:
        - "0.10.0/jquery.timeago.js"

