---
  name: "Gritter"
  stable: "1.7.3"
  copyright: "Copyright (c) 2012 Jordan Boesch."
  license: "MIT and GPL License"
  author: "Jordan Boesch"
  url: "http://boedesign.com/blog/2009/07/11/growl-for-jquery-gritter/"
  latest: "1.7.3"
  demo_url: "http://boedesign.com/demos/gritter/"
  description: "For those who don’t know what Growl is, it’s basically a notification bubble/popup that appears in the top right of your desktop."
  packages:
    1.7.3:
      source:
        - "1.7.3/js/jquery.gritter.js"
      style:
        - "1.7.3/css/jquery.gritter.css"

