---
  name: "Infinite Scroll"
  stable: "2.0b2.120311"
  copyright: "Copyright 2011 Paul Irish & Luke Shumard"
  license: "Licensed under the MIT license"
  author: "Paul Irish"
  url: "http://www.infinite-scroll.com/infinite-scroll-jquery-plugin/"
  latest: "2.0b2.120311"
  demo_url: "http://www.infinite-scroll.com/trigger.html"
  description: "This plugin aims to progressively enhance your page. Your navigation/pagination elements should be present in the HTML for non-js users, but the plugin will utilize those links to build out a more rich browsing experience."
  packages:
    2.0b2.120311:
      source:
        - "2.0b2.120311/jquery.infinitescroll.js"

