---
  name: "Curtain.js"
  stable: "1.4.1"
  copyright: "Copyright 2011, Victor Coulon"
  license: "MIT License"
  author: "Victor Coulon"
  url: "http://victorcoulon.fr"
  latest: "2.0"
  packages: 
    2.0:
      source:
        - "2.0/curtain.js"
      style:
        - "2.0/curtain.js"
  
    1.4.1: 
      source: 
        - "1.4.1/curtain.js"
      style: 
        - "1.4.1/curtain.css"

