---
  name: "Hoverizr"
  stable: "1.0"
  copyright: "CC 2011, Ilias Iovis"
  license: "Creative Commons"
  author: "Ilias Iovis"
  url: "http://www.iliasiovis.com/hoverizr/"
  latest: "1.0"
  packages: 
    1.0: 
      source: 
        - "1.0/jquery.hoverizr.js"

