---
  name: "Tiny Carousel"
  stable: "1.9"
  copyright: " Copyright 2010, Maarten Baijs."
  license: "Dual licensed under the MIT or GPL Version 2 licenses"
  author: "Maarten Baijs"
  url: "http://baijs.nl/tinycarousel/"
  demo_url: "http://baijs.nl/tinycarousel/"
  description: "Tiny Carousel is a lightweight carousel for sliding html based content. It was built using the javascript jQuery library."
  latest: "1.9"
  packages:
    1.9:
      source:
        - "1.9/jquery.tinycarousel.js"

