---
  name: "jquery.scrollpath.js"
  stable: "1.1.1"
  copyright: "Copyright, Joel Besada"
  license: "MIT License"
  author: "Joel Besada"
  url: "http://joelb.me/scrollpath"
  demo_url: "http://joelb.me/scrollpath"
  description: "A plugin for defining custom scroll paths."
  latest: "1.1.1"
  packages:
    1.1.1:
      requires:
        - "easing"
        - "prefixfree"
      source:
        - "1.1.1/jquery.scrollpath.js"
      style:
        - "1.4.1/scrollpath.css"

