---
  name: "jquery.scrollorama.js"
  stable: "0.1.1"
  copyright: "Copyright, John Polacek"
  license: "MIT and GPL"
  author: "John Polacek"
  url: "http://johnpolacek.github.com/scrollorama/"
  latest: "0.1.1"
  packages: 
    0.1.1: 
      source: 
        - "0.1.1/jquery.scrollorama.js"

    0.1:
      source:
        - "0.1/jquery.scrollorama.js"

