---
  name: "jQuery Masonry"
  stable: "2.1.03"
  copyright: "Copyright 2012 David DeSandro"
  license: "Licensed under the MIT license"
  author: "David DeSandro"
  url: "http://masonry.desandro.com"
  latest: "2.1.03"
  packages: 
    2.1.03: 
      source: 
        - "2.1.03/jquery.masonry.js"

