---
  name: "Fancybox"
  stable: "1.3.4"
  copyright: "Copyright (c) 2008 - 2010 Janis Skarnelis"
  license: "Dual licensed under the MIT and GPL licenses"
  author: "Janis Skarnelis"
  url: "http://fancybox.net/"
  demo_url: "http://fancybox.net/"
  description: "FancyBox is a tool for displaying images, html content and multi-media in a Mac-style \"lightbox\" that floats overtop of web page."
  latest: "1.3.4"
  packages:
    1.3.4:
      requires:
        - "easing"
        - "mousewheel"
      source:
        - "1.3.4/jquery.fancybox-1.3.4.js"
      style:
        - "1.3.4/jquery.fancybox-1.3.4.css"

