---
  name: "Responsive Slides"
  stable: "1.24"
  copyright: "Copyright (c) 2011-2012 Viljami Salminen"
  license: "MIT License"
  author: "Viljami Salminen"
  url: "http://responsive-slides.viljamis.com/"
  demo_url: "http://responsive-slides.viljamis.com/"
  description: "ResponsiveSlides.js is a tiny jQuery plugin that creates a responsive slider using list items inside <ul>."
  latest: "1.24"
  packages:
    1.24:
      source:
        - "1.24/responsiveslides.js"
      style:
        - "1.24/responsiveslides.css"

