---
  name: "jQuery.picker"
  stable: "0.1"
  copyright: "Copyright 2012 José Carlos Nieto."
  license: "MIT License"
  author: "José Carlos Nieto"
  url: "http://xiam.menteslibres.org/p/jquery-picker"
  latest: "0.1"
  packages: 
    0.1: 
      source: 
        - "0.1/jquery.picker.js"
      style: 
        - "0.1/jquery.picker.css"

