---
  name: "jQuery.scrollTo"
  stable: "1.4.3.1"
  copyright: "Copyright (c) 2007-2009 Ariel Flesler"
  license: "MIT License, GPL License"
  author: "Ariel Flesler"
  url: "http://flesler.blogspot.mx/2009/05/jqueryscrollto-142-released.html"
  latest: "1.4.3.1"
  packages:
    1.4.3.1:
      source:
        - "1.4.3.1/jquery.scrollTo-1.4.3.1.js" 
    1.4.2: 
      source: 
        - "1.4.2/jquery.scrollTo-1.4.2.js"

