---
  name: "jquery.scrolldeck.js"
  stable: "0.1.1"
  copyright: "Copyright, John Polacek"
  license: "MIT and GPL"
  author: "John Polacek"
  url: "https://github.com/johnpolacek/scrolldeck.js"
  latest: "0.1.1"
  packages: 
    0.1.1: 
      requires: 
        - "scrollorama"
        - "easing"
        - "scrollto"
      source: 
        - "0.1.1/jquery.scrolldeck.js"
    
    0.1:
      requires:
        - "scrollorama"
        - "easing"
        - "scrollto"
      source:
        - "0.1/jquery.scrolldeck.js"

