---
  name: "jQuery.tinyscrollbar"
  stable: "1.8"
  copyright: " Copyright 2010, Maarten Baijs."
  license: "Dual licensed under the MIT or GPL Version 2 licenses"
  author: "Maarten Baijs"
  url: "http://baijs.nl/tinyscrollbar/"
  latest: "1.8"
  packages:
    1.8:
      source:
        - "1.8/jquery.tinyscrollbar.js" 
    1.66: 
      source: 
        - "1.66/jquery.tinyscrollbar.js"

