---
  name: "Underscore"
  stable: "1.4.2"
  copyright: "(c) 2009-2012 Jeremy Ashkenas, DocumentCloud Inc."
  license: "MIT License"
  author: "Jeremy Ashkenas"
  url: "http://underscorejs.org/"
  description: "Underscore is a utility-belt library for JavaScript that provides a lot of the functional programming support that you would expect in Prototype.js (or Ruby), but without extending any of the built-in JavaScript objects. It's the tie to go along with jQuery's tux, and Backbone.js's suspenders."
  latest: "1.4.2"
  packages:
    1.4.2:
      source:
        - "1.4.2/underscore.js"

