---
  name: "jQuery Montage plugin"
  stable: "latest"
  copyright: "Copyright 2011, Pedro Botelho"
  license: "MIT License"
  author: "Pedro Botelho"
  url: "http://www.codrops.com/"
  latest: "latest"
  packages: 
    latest: 
      source: 
        - "latest/jquery.montage.js"
      style: 
        - "latest/style.css"

